name: PlatformIO Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ./target
          key: project-build

      - uses: dtolnay/rust-toolchain@nightly

      - name: Build the project
        run: cargo build --release
